[build-system]
requires = ["setuptools>=64"]
build-backend = "setuptools.build_meta"

[project]
name = "pnptool"
version = "0.1"
requires-python = ">=3.12"
authors = [{name="Jan Musílek", email="stinovlas@gmail.com" }]
description = "Print and play toolbox"
readme = "README.md"
dependencies = [
  "pypdf[image]",
  "reportlab",
  "click",
  "cloup",
  "rich",
]

[project.scripts]
pnptool = "pnptool.main:cli"


[tool.ruff.lint]
select = ["E4", "E7", "E9", "F", "C90", "I", "S"]
ignore = []
